#pragma once 
#include "flight.h"
#include <unistd.h>
/******************************替换G的飞机字符图******************************************/
static inline void Show(unsigned long ms){
	unsigned long i = 100000;
	while(i <= ms){
		system("clear");
		printf(LIGHT_CYAN"***********************************************************************************************************************************************************\n"NONE);	
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                               中国航班系统                                                                                      \n"NONE);
		printf(LIGHT_CYAN"**********                                          Wecome to airline system                                                                               \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                    温馨提示：请选择登录模式：                                                                                   \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                             1 输入1进入管理员模式；                                                                             \n"NONE);
		printf(LIGHT_CYAN"**********                                             2 输入2进入用户模式；                                                                               \n"NONE);
		printf(LIGHT_CYAN"**********                                             3 输入3进入退出系统；                                                                               \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"***********************************************************************************************************************************************************\n"NONE);

		usleep(i);
		system("clear");
		/******************************替换G的飞机字符图******************************************/
		printf(LIGHT_BLUE"***********************************************************************************************************************************************************\n"NONE);	
		printf(LIGHT_BLUE"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_BLUE"**********                                                                           D                                                                     \n"NONE);
		printf(LIGHT_BLUE"**********                                                                        i   W                                                                    \n"NONE);
		printf(LIGHT_BLUE"**********                                                                      E                                                                          \n"NONE);
		printf(LIGHT_BLUE"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_BLUE"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_BLUE"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_BLUE"**********                                                                              f                                                                  \n"NONE);
		printf(LIGHT_BLUE"**********                                                               i            G                                                                    \n"NONE);
		printf(LIGHT_BLUE"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_BLUE"**********                                                                  G      L                                 t                                     \n"NONE);
		printf(LIGHT_BLUE"**********                                             ,         G:                   E                                                                    \n"NONE);
		printf(LIGHT_BLUE"**********                                             i          i      D                                     :      L                                    \n"NONE);
		printf(LIGHT_BLUE"**********                                         G                    :      ;                                ,                                          \n"NONE);
		printf(LIGHT_BLUE"**********                                               中国航班系统          t      D                             EG                                     \n"NONE);
		printf(LIGHT_BLUE"**********                                          ecome to airline system           f         E;                                                         \n"NONE);
		printf(LIGHT_BLUE"**********                                                                                       :j                G        E                              \n"NONE);
		printf(LIGHT_BLUE"**********                                    E :   温馨提示：请选择登录模式：                                                                             \n"NONE);
		printf(LIGHT_BLUE"**********                                   ;                                                                                                             \n"NONE);
		printf(LIGHT_BLUE"**********                                 :                    1 输入1进入管理员模式；                                                                    \n"NONE);
		printf(LIGHT_BLUE"**********                                          j           2 输入2进入用户模式；                                                                      \n"NONE);
		printf(LIGHT_BLUE"**********                              L G  ,                  3 输入3进入退出系统；                                                                      \n"NONE);
		printf(LIGHT_BLUE"**********                               i  ;  i                                                                                                           \n"NONE);
		printf(LIGHT_BLUE"**********                               ,                       E;    ;                                                                                   \n"NONE);
		printf(LIGHT_BLUE"**********                                                                                               E   E        G t G                                \n"NONE);
		printf(LIGHT_BLUE"**********                                                   L                                       t                   ,                                 \n"NONE);
		printf(LIGHT_BLUE"**********                                          G:      :f                             j                           ;                                   \n"NONE);
		printf(LIGHT_BLUE"**********                                        ;:D        E                 f                                              ;                            \n"NONE);
		printf(LIGHT_BLUE"**********                                                         j   ,G    t                                                                             \n"NONE);
		printf(LIGHT_BLUE"**********                                                      ;                                                                                          \n"NONE);
		printf(LIGHT_BLUE"**********                                                      L                                                                                          \n"NONE);
		printf(LIGHT_BLUE"**********                                                            j    L                                                                               \n"NONE);
		printf(LIGHT_BLUE"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_BLUE"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_BLUE"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_BLUE"**********                                                        L                                                                                        \n"NONE);
		printf(LIGHT_BLUE"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_BLUE"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_BLUE"**********                                                          t ft                                                                                   \n"NONE);
		printf(LIGHT_BLUE"***********************************************************************************************************************************************************\n"NONE);

		usleep(i);
		system("clear");
		/******************************替换K的飞机字符图******************************************/
		printf(LIGHT_PURPLE"***********************************************************************************************************************************************************\n"NONE);	
		printf(LIGHT_PURPLE"**********                             ..  .                    .. .         ..                      ...            ..  .                                  \n"NONE);
		printf(LIGHT_PURPLE"**********                              .                   ..  .             .   E  D            ..  .              .                                     \n"NONE);
		printf(LIGHT_PURPLE"**********                               .                  ..                    i   W.          ..                  .                                    \n"NONE);
		printf(LIGHT_PURPLE"**********                                                .                     E               . .                                                        \n"NONE);
		printf(LIGHT_PURPLE"**********                                                   .                                     .                                                       \n"NONE);
		printf(LIGHT_PURPLE"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_PURPLE"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_PURPLE"**********                                      .                                     . f                                  .                               \n"NONE);
		printf(LIGHT_PURPLE"**********                                   ... .                       i         ...G                                       .                            \n"NONE);
		printf(LIGHT_PURPLE"**********                                .                   ..   .         .       .              ..   .          .                                      \n"NONE);
		printf(LIGHT_PURPLE"**********                                 .                    .           G      L               .. .              t  .                                  \n"NONE);
		printf(LIGHT_PURPLE"**********                             . .             ,         G:                   E           ...                                                      \n"NONE);
		printf(LIGHT_PURPLE"**********                                             i  .   ..  i      D                      . . ..         :      L                                    \n"NONE);
		printf(LIGHT_PURPLE"**********                                         G     ... .          :      ;                 . .            ,                                          \n"NONE);
		printf(LIGHT_PURPLE"**********                                               中国航班系统  .       t      D.         .                  EG                                     \n"NONE);
		printf(LIGHT_PURPLE"**********                                          ecome to airline system           f         E;               .         .                               \n"NONE);
		printf(LIGHT_PURPLE"**********                                                                                       :j                G        E                              \n"NONE);
		printf(LIGHT_PURPLE"**********                                    E :   温馨提示：请选择登录模式：                                                                             \n"NONE);
		printf(LIGHT_PURPLE"**********                                   ;                                                                                                             \n"NONE);
		printf(LIGHT_PURPLE"**********                                 :    .    .          1.输入1进入管理员模式；                                                                    \n"NONE);
		printf(LIGHT_PURPLE"**********                                  .    . .j           2.输入2进入用户模式；                                      .  .                            \n"NONE);
		printf(LIGHT_PURPLE"**********                              L G  ,.                 3.输入3进入退出系统；                  .                   .                               \n"NONE);
		printf(LIGHT_PURPLE"**********                               i .;  i    .                                                 . .               .  .                               \n"NONE);
		printf(LIGHT_PURPLE"**********                               , .                 .   E;    ;       . .                 .                ... .  .                               \n"NONE);
		printf(LIGHT_PURPLE"**********                                                .                                     ..  .    E   E        G t G                                \n"NONE);
		printf(LIGHT_PURPLE"**********                                                   L                                       t                   ,                                 \n"NONE);
		printf(LIGHT_PURPLE"**********                                          G:      :f                             j.                          ;                                   \n"NONE);
		printf(LIGHT_PURPLE"**********                                        ;:D        E                 f                                              ;                            \n"NONE);
		printf(LIGHT_PURPLE"**********                                     .                   j.  ,G    t     . .                                     ..                              \n"NONE);
		printf(LIGHT_PURPLE"**********                             ..                       ;.               .                    ..            ..  .                                  \n"NONE);
		printf(LIGHT_PURPLE"**********                              .  .                 .  L                .                 .  .              .  .                                  \n"NONE);
		printf(LIGHT_PURPLE"**********                                                            j    L                                                                               \n"NONE);
		printf(LIGHT_PURPLE"**********                                  ...  .                                ...  .                                  ..  .                            \n"NONE);
		printf(LIGHT_PURPLE"**********                                 .  .                  .               .  .                                  ..  .                               \n"NONE);
		printf(LIGHT_PURPLE"**********                                ....                    .             ....                    .               ...                                \n"NONE);
		printf(LIGHT_PURPLE"**********                                .                    .  L.          . .                   ..   .             .                                   \n"NONE);
		printf(LIGHT_PURPLE"**********                              .  .                  . .             .  .                  . .              .  .                                  \n"NONE);
		printf(LIGHT_PURPLE"**********                             . .                  ...              . .                  ...               . .                                    \n"NONE);
		printf(LIGHT_PURPLE"**********                                                .   .     t ft                        .  ..                                                      \n"NONE);
		printf(LIGHT_PURPLE"***********************************************************************************************************************************************************\n"NONE);


		usleep(i);
		system("clear");
		/******************************替换W的飞机字符图******************************************/
		printf(YELLOW"***********************************************************************************************************************************************************\n"NONE);	
		printf(YELLOW"**********                             ..  .                    .. .         ..                      ...            ..  .                                  \n"NONE);
		printf(YELLOW"**********                              .                   ..  .             .   E  D            ..  .              .                                     \n"NONE);
		printf(YELLOW"**********                               .                  ..                    i   W.          ..                  .                                    \n"NONE);
		printf(YELLOW"**********                                                .                     E               . .                                                        \n"NONE);
		printf(YELLOW"**********                                                   .                                     .                                                       \n"NONE);
		printf(YELLOW"**********                                                                                                                                                 \n"NONE);
		printf(YELLOW"**********                                                                                                                                                 \n"NONE);
		printf(YELLOW"**********                                      .                                  KK . f                                  .                               \n"NONE);
		printf(YELLOW"**********                                   ... .                       i         ...G                                  K    .                            \n"NONE);
		printf(YELLOW"**********                                .                   ..   .         .       .K             ..   .          .                                      \n"NONE);
		printf(YELLOW"**********                                 .                    .           G      L               .. .              t  .                                  \n"NONE);
		printf(YELLOW"**********                             . .             ,         G:                   E           ...                        K                             \n"NONE);
		printf(YELLOW"**********                                             i  .   ..  i      D                      . . ..         :      L                                    \n"NONE);
		printf(YELLOW"**********                                         G     ... .          :      ;                 . .            , K                                        \n"NONE);
		printf(YELLOW"**********                                               中国航班系统  .       t      D.         .                  EG                                     \n"NONE);
		printf(YELLOW"**********                                          ecome to airline system           f         E;               .         .                               \n"NONE);
		printf(YELLOW"**********                                    K                                                  :jK               G        E                              \n"NONE);
		printf(YELLOW"**********                                    E :   温馨提示：请选择登录模式：                                            K                                \n"NONE);
		printf(YELLOW"**********                                   ;  K                                                                                                          \n"NONE);
		printf(YELLOW"**********                                 :    .    .          1.输入1进入管理员模式；                                                                    \n"NONE);
		printf(YELLOW"**********                                  .    . .j K         2.输入2进入用户模式；                                      .  .                            \n"NONE);
		printf(YELLOW"**********                              L G  ,.       K         3.输入3进入退出系统；                  .                   .                               \n"NONE);
		printf(YELLOW"**********                              Ki .;  i    . K                                               . .               .  .                               \n"NONE);
		printf(YELLOW"**********                               , .                 .   E;    ;K   K  . .                 .                ... .  .                               \n"NONE);
		printf(YELLOW"**********                                                .                                     ..  .    EK  E        G t G                                \n"NONE);
		printf(YELLOW"**********                                                   L                                       t                   ,                                 \n"NONE);
		printf(YELLOW"**********                                          G:      :fK                 K          j.                          ;                                   \n"NONE);
		printf(YELLOW"**********                                        ;:D        E                 f                                             K;                            \n"NONE);
		printf(YELLOW"**********                                     .               K   j.  ,G    t     . .                                     ..                              \n"NONE);
		printf(YELLOW"**********                             ..                      K;.               .                    ..            ..  .                                  \n"NONE);
		printf(YELLOW"**********                              .  .                 .  L                .                 .  .              .  .                                  \n"NONE);
		printf(YELLOW"**********                                                            j    LK                                                                              \n"NONE);
		printf(YELLOW"**********                                  ...  .                                ...  .                                  ..  .                            \n"NONE);
		printf(YELLOW"**********                                 .  .                  .               .  .                                  ..  .                               \n"NONE);
		printf(YELLOW"**********                                ....                    .       K     ....                    .               ...                                \n"NONE);
		printf(YELLOW"**********                                .                    .  L.          . .                   ..   .             .                                   \n"NONE);
		printf(YELLOW"**********                              .  .                  . . K           .  .                  . .              .  .                                  \n"NONE);
		printf(YELLOW"**********                             . .                  ...        K     . .                  ...               . .                                    \n"NONE);
		printf(YELLOW"**********                                                .   .     t ft                        .  ..                                                      \n"NONE);
		printf(YELLOW"***********************************************************************************************************************************************************\n"NONE);

		usleep(i);
		system("clear");
		/******************************替换#的飞机字符图******************************************/
		printf(WHITE"***********************************************************************************************************************************************************\n"NONE);	
		printf(WHITE"**********                             ..  .                    .. .         ..                      ...            ..  .                                  \n"NONE);
		printf(WHITE"**********                              .                   ..  .             .   E  D            ..  .              .                                     \n"NONE);
		printf(WHITE"**********                               .                  ..                    i   W.          ..                  .                                    \n"NONE);
		printf(WHITE"**********                                                .                    WE               . .                                                        \n"NONE);
		printf(WHITE"**********                                                   .                         W           .                                                       \n"NONE);
		printf(WHITE"**********                                                                                                                                                 \n"NONE);
		printf(WHITE"**********                                                                  W  W                                                                           \n"NONE);
		printf(WHITE"**********                                      .                         W        KKW.Wf                                  .                               \n"NONE);
		printf(WHITE"**********                                   ... .                       i         ...G                                 WKWW  .                            \n"NONE);
		printf(WHITE"**********                                .                   ..   .  W      . W     .K             ..   .          .  W     W                             \n"NONE);
		printf(WHITE"**********                                 .                    .        W  G     WL               .. .              t  .    W                             \n"NONE);
		printf(WHITE"**********                             . .             ,W        G:           W      WE           ...                 W      K                             \n"NONE);
		printf(WHITE"**********                                             i  .   ..  i   W  D       W   W          . . ..       W : W    L                                    \n"NONE);
		printf(WHITE"**********                                         G     ... .          :   W  ;     W           . .          W , K  W                                     \n"NONE);
		printf(WHITE"**********                                               中国航班系统  .       t      D.         .                  EG      W                              \n"NONE);
		printf(WHITE"**********                                         Wecome to airline system           f   WW    E;           W   .         .                               \n"NONE);
		printf(WHITE"**********                                    K                                                  :jK      WWWW     G        E                              \n"NONE);
		printf(WHITE"**********                                   WEW:   温馨提示：请选择登录模式：                                            K                                \n"NONE);
		printf(WHITE"**********                                   ;  K                                                                                                          \n"NONE);
		printf(WHITE"**********                                 :    . W  .          1.输入1进入管理员模式；                                                                    \n"NONE);
		printf(WHITE"**********                                  .    . .j K         2.输入2进入用户模式；                                      .  .                            \n"NONE);
		printf(WHITE"**********                              L G W,.       K         3.输入3进入退出系统；                  .                   .                               \n"NONE);
		printf(WHITE"**********                              Ki .;W i    . K                                               . .               .  .                               \n"NONE);
		printf(WHITE"**********                               , .                 . WWE;    ;K  WK  . .                 .             W  ... .  .                               \n"NONE);
		printf(WHITE"**********                                                .                      W              ..  .  W EK  E        GWt GW                               \n"NONE);
		printf(WHITE"**********                                  W                L                   W     WWW       WW  t                 W ,                                 \n"NONE);
		printf(WHITE"**********                                          G:      :fK                 KW  WW    Wj.                          ;W                                  \n"NONE);
		printf(WHITE"**********                                      W ;:D        EW                fW                                            K;                            \n"NONE);
		printf(WHITE"**********                                     .               KW  j.  ,G  W tW    . .                                     ..                              \n"NONE);
		printf(WHITE"**********                             ..                      K;.           W   .                    ..            ..  .                                  \n"NONE);
		printf(WHITE"**********                              .  .                 . WL            W   .                 .  .              .  .                                  \n"NONE);
		printf(WHITE"**********                                                            j  W LK                                                                              \n"NONE);
		printf(WHITE"**********                                  ...  .              W          W      ...  .                                  ..  .                            \n"NONE);
		printf(WHITE"**********                                 .  .                  .               .  .                                  ..  .                               \n"NONE);
		printf(WHITE"**********                                ....                    .       K     ....                    .               ...                                \n"NONE);
		printf(WHITE"**********                                .                    .  L.     W    . .                   ..   .             .                                   \n"NONE);
		printf(WHITE"**********                              .  .                  . . K           .  .                  . .              .  .                                  \n"NONE);
		printf(WHITE"**********                             . .                  ...    W   K     . .                  ...               . .                                    \n"NONE);
		printf(WHITE"**********                                                .   .     t ft                        .  ..                                                      \n"NONE);
		printf(WHITE"***********************************************************************************************************************************************************\n"NONE);

		usleep(i);
		system("clear");


		/******************************替换##的飞机字符图******************************************/
		printf(BROWN"***********************************************************************************************************************************************************\n"NONE);	
		printf(BROWN"**********                             ..  .                    .. .         ..                      ...            ..  .                                  \n"NONE);
		printf(BROWN"**********                              .                   ..  .             .   E  D            ..  .              .                                     \n"NONE);
		printf(BROWN"**********                               .                  ..                    i  #W.          ..                  .                                    \n"NONE);
		printf(BROWN"**********                                                .                    WE               . .                                                        \n"NONE);
		printf(BROWN"**********                                                   .                #        W           .                                                       \n"NONE);
		printf(BROWN"**********                                                                                                                                                 \n"NONE);
		printf(BROWN"**********                                                                 #W  W#                                                                          \n"NONE);
		printf(BROWN"**********                                      .                         W        KKW.Wf                                  .                               \n"NONE);
		printf(BROWN"**********                                   ... .                      #i         ...G#                                WKWW# .                            \n"NONE);
		printf(BROWN"**********                                .                   ..   .  W      .#W#    .K             ..   .          .# W     W                             \n"NONE);
		printf(BROWN"**********                                 .                    .        W  G    #WL               .. .             #t# .    W                             \n"NONE);
		printf(BROWN"**********                             . .             ,W        G:           W#     WE           ...           #   # W      K                             \n"NONE);
		printf(BROWN"**********                                             i  .   ..  i  #W  D      #W#  W          . . ..       W :#W   #L      #                             \n"NONE);
		printf(BROWN"**********                                         G     ... .          :  #W  ;     W           . .         #W#, K# W                                     \n"NONE);
		printf(BROWN"**********                                               中国航班系统  .       t      D.         .           #    # EG      W                              \n"NONE);
		printf(BROWN"**********                                         Wecome to airline system           f  #WW    E;           W   .# #      .#                              \n"NONE);
		printf(BROWN"**********                                   #K                                                  :jK      WWWW     G#      #E                              \n"NONE);
		printf(BROWN"**********                                   WEW:   温馨提示：请选择登录模式：                                  #  #      K#                               \n"NONE);
		printf(BROWN"**********                                   ; #K#                                                                        #                                \n"NONE);
		printf(BROWN"**********                                #:#   .#W  .          1.输入1进入管理员模式；                                   #                                \n"NONE);
		printf(BROWN"**********                                 #.    . .j#K         2.输入2进入用户模式；                                     #.  .                            \n"NONE);
		printf(BROWN"**********                              L#G#W,.       K#        3.输入3进入退出系统；                  .                 # .                               \n"NONE);
		printf(BROWN"**********                              Ki#.;W#i    .#K                                               . .               .# .                               \n"NONE);
		printf(BROWN"**********                               , .                 . WWE;    ;K  WK  . .                 .             W# ... . #.                               \n"NONE);
		printf(BROWN"**********                                                .                     #W              ..  .  W#EK  E        GWt GW                               \n"NONE);
		printf(BROWN"**********                                 #W                L#                 #W    #WWW      #WW  t                #W#,    #                            \n"NONE);
		printf(BROWN"**********                                         #G:      :fK                 KW  WW    Wj.                          ;W#    #                            \n"NONE);
		printf(BROWN"**********                                     #W#;:D        EW                fW#                                           K;                            \n"NONE);
		printf(BROWN"**********                                     .               KW  j.  ,G  W#tW#   . .                                     ..                              \n"NONE);
		printf(BROWN"**********                             ..                      K;.           W#  .                    ..            ..  .                                  \n"NONE);
		printf(BROWN"**********                              .  .                 . WL            W   .                 .  .              .  .                                  \n"NONE);
		printf(BROWN"**********                                                            j  W#LK                                                                              \n"NONE);
		printf(BROWN"**********                                  ...  .              W          W      ...  .                                  ..  .                            \n"NONE);
		printf(BROWN"**********                                 .  .                 #.               .  .                                  ..  .                               \n"NONE);
		printf(BROWN"**********                                ....                   #.       K     ....                    .               ...                                \n"NONE);
		printf(BROWN"**********                                .                    . #L.     W#   . .                   ..   .             .                                   \n"NONE);
		printf(BROWN"**********                              .  .                  . . K           .  .                  . .              .  .                                  \n"NONE);
		printf(BROWN"**********                             . .                  ...    W  #K#    . .                  ...               . .                                    \n"NONE);
		printf(BROWN"**********                                                .   .     t#ft                        .  ..                                                      \n"NONE);
		printf(BROWN"***********************************************************************************************************************************************************\n"NONE);

		usleep(i);
		system("clear");

		printf(GREEN"***********************************************************************************************************************************************************\n"NONE);	
		printf(GREEN"**********                             ..  .                    .. .         ..                      ...            ..  .                                  \n"NONE);
		printf(GREEN"**********                              .                   ..  .             .   E  D            ..  .              .                                     \n"NONE);
		printf(GREEN"**********                               .                  ..                  ##i  #W.          ..                  .                                    \n"NONE);
		printf(GREEN"**********                                                .                    WE     ##        . .                                                        \n"NONE);
		printf(GREEN"**********                                                   .                #        W           .                                                       \n"NONE);
		printf(GREEN"**********                                                                   ######    ##                                                                  \n"NONE);
		printf(GREEN"**********                                                                 #W##W#    ####                                                                  \n"NONE);
		printf(GREEN"**********                                      .                         W        KKW.Wf                                  .                               \n"NONE);
		printf(GREEN"**********                                   ... .                      #i         ...G#                                WKWW# .                            \n"NONE);
		printf(GREEN"**********                                .                   ..   .  W      .#W#    .K             ..   .          .# W     W                             \n"NONE);
		printf(GREEN"**********                                 .                    .    ####W##G    #WL ##            .. .             #t# .    W                             \n"NONE);
		printf(GREEN"**********                             . .             ,W########G: ##      ##W#   ##WE           ...         ###   # W      K                             \n"NONE);
		printf(GREEN"**********                                         ####i  .   ..  i###W##D      #W#  W          . . ..       W :#W## #L      #                             \n"NONE);
		printf(GREEN"**********                                       ##G     ... .          :###W##;   ##W           . .         #W#, K# W      ##                             \n"NONE);
		printf(GREEN"**********                                     ##        中国航班系统  .       t######D.         .           #    # EG      W                              \n"NONE);
		printf(GREEN"**********                                    ##   Wecome to airline system           f###WW####E;           W   .# #      .#                              \n"NONE);
		printf(GREEN"**********                                   #K                                                  :jK######WWWW#### G#      #E                              \n"NONE);
		printf(GREEN"**********                                 ##WEW:   温馨提示：请选择登录模式：                                  #  #      K#                               \n"NONE);
		printf(GREEN"**********                                 ##; #K#                                                                        #                                \n"NONE);
		printf(GREEN"**********                                #:#   .#W##.          1.输入1进入管理员模式；                                   #                                \n"NONE);
		printf(GREEN"**********                               ###.    . .j#K         2.输入2进入用户模式；                                     #.  .                            \n"NONE);
		printf(GREEN"**********                              L#G#W,.       K#        3.输入3进入退出系统；                  .                 # .                               \n"NONE);
		printf(GREEN"**********                              Ki#.;W#i    .#K                                               . .               .# .                               \n"NONE);
		printf(GREEN"**********                             ##, .                 . WWE;    ;K##WK##. .                 .             W# ... . #.                               \n"NONE);
		printf(GREEN"**********                               ##               .  ##                 #W              ..  .##W#EK##E      ##GWt GW##                             \n"NONE);
		printf(GREEN"**********                                 #W##              L#                 #W#####WWW#######WW##t                #W#,    #                            \n"NONE);
		printf(GREEN"**********                                   #######G:      :fK                 KW##WW####Wj.                          ;W#    #                            \n"NONE);
		printf(GREEN"**********                                     #W#;:D########EW                fW#                                       ####K;                            \n"NONE);
		printf(GREEN"**********                                     .               KW##j.  ,G##W#tW#   . .                                     ..                              \n"NONE);
		printf(GREEN"**********                             ..                      K;.           W#  .                    ..            ..  .                                  \n"NONE);
		printf(GREEN"**********                              .  .                 . WL            W   .                 .  .              .  .                                  \n"NONE);
		printf(GREEN"**********                                                     ##     j##W#LK                                                                              \n"NONE);
		printf(GREEN"**********                                  ...  .              W          W      ...  .                                  ..  .                            \n"NONE);
		printf(GREEN"**********                                 .  .                 #.        ##     .  .                                  ..  .                               \n"NONE);
		printf(GREEN"**********                                ....                   #.       K     ....                    .               ...                                \n"NONE);
		printf(GREEN"**********                                .                    . #L.     W#   . .                   ..   .             .                                   \n"NONE);
		printf(GREEN"**********                              .  .                  . . K     ##    .  .                  . .              .  .                                  \n"NONE);
		printf(GREEN"**********                             . .                  ...    W###K#    . .                  ...               . .                                    \n"NONE);
		printf(GREEN"**********                                                .   .     t#ft                        .  ..                                                      \n"NONE);
		printf(GREEN"***********************************************************************************************************************************************************\n"NONE);
		usleep(i);
		/******************************替换##的飞机字符图******************************************/
		printf(BROWN"***********************************************************************************************************************************************************\n"NONE);	
		printf(BROWN"**********                             ..  .                    .. .         ..                      ...            ..  .                                  \n"NONE);
		printf(BROWN"**********                              .                   ..  .             .   E  D            ..  .              .                                     \n"NONE);
		printf(BROWN"**********                               .                  ..                    i  #W.          ..                  .                                    \n"NONE);
		printf(BROWN"**********                                                .                    WE               . .                                                        \n"NONE);
		printf(BROWN"**********                                                   .                #        W           .                                                       \n"NONE);
		printf(BROWN"**********                                                                                                                                                 \n"NONE);
		printf(BROWN"**********                                                                 #W  W#                                                                          \n"NONE);
		printf(BROWN"**********                                      .                         W        KKW.Wf                                  .                               \n"NONE);
		printf(BROWN"**********                                   ... .                      #i         ...G#                                WKWW# .                            \n"NONE);
		printf(BROWN"**********                                .                   ..   .  W      .#W#    .K             ..   .          .# W     W                             \n"NONE);
		printf(BROWN"**********                                 .                    .        W  G    #WL               .. .             #t# .    W                             \n"NONE);
		printf(BROWN"**********                             . .             ,W        G:           W#     WE           ...           #   # W      K                             \n"NONE);
		printf(BROWN"**********                                             i  .   ..  i  #W  D      #W#  W          . . ..       W :#W   #L      #                             \n"NONE);
		printf(BROWN"**********                                         G     ... .          :  #W  ;     W           . .         #W#, K# W                                     \n"NONE);
		printf(BROWN"**********                                               中国航班系统  .       t      D.         .           #    # EG      W                              \n"NONE);
		printf(BROWN"**********                                         Wecome to airline system           f  #WW    E;           W   .# #      .#                              \n"NONE);
		printf(BROWN"**********                                   #K                                                  :jK      WWWW     G#      #E                              \n"NONE);
		printf(BROWN"**********                                   WEW:   温馨提示：请选择登录模式：                                  #  #      K#                               \n"NONE);
		printf(BROWN"**********                                   ; #K#                                                                        #                                \n"NONE);
		printf(BROWN"**********                                #:#   .#W  .          1.输入1进入管理员模式；                                   #                                \n"NONE);
		printf(BROWN"**********                                 #.    . .j#K         2.输入2进入用户模式；                                     #.  .                            \n"NONE);
		printf(BROWN"**********                              L#G#W,.       K#        3.输入3进入退出系统；                  .                 # .                               \n"NONE);
		printf(BROWN"**********                              Ki#.;W#i    .#K                                               . .               .# .                               \n"NONE);
		printf(BROWN"**********                               , .                 . WWE;    ;K  WK  . .                 .             W# ... . #.                               \n"NONE);
		printf(BROWN"**********                                                .                     #W              ..  .  W#EK  E        GWt GW                               \n"NONE);
		printf(BROWN"**********                                 #W                L#                 #W    #WWW      #WW  t                #W#,    #                            \n"NONE);
		printf(BROWN"**********                                         #G:      :fK                 KW  WW    Wj.                          ;W#    #                            \n"NONE);
		printf(BROWN"**********                                     #W#;:D        EW                fW#                                           K;                            \n"NONE);
		printf(BROWN"**********                                     .               KW  j.  ,G  W#tW#   . .                                     ..                              \n"NONE);
		printf(BROWN"**********                             ..                      K;.           W#  .                    ..            ..  .                                  \n"NONE);
		printf(BROWN"**********                              .  .                 . WL            W   .                 .  .              .  .                                  \n"NONE);
		printf(BROWN"**********                                                            j  W#LK                                                                              \n"NONE);
		printf(BROWN"**********                                  ...  .              W          W      ...  .                                  ..  .                            \n"NONE);
		printf(BROWN"**********                                 .  .                 #.               .  .                                  ..  .                               \n"NONE);
		printf(BROWN"**********                                ....                   #.       K     ....                    .               ...                                \n"NONE);
		printf(BROWN"**********                                .                    . #L.     W#   . .                   ..   .             .                                   \n"NONE);
		printf(BROWN"**********                              .  .                  . . K           .  .                  . .              .  .                                  \n"NONE);
		printf(BROWN"**********                             . .                  ...    W  #K#    . .                  ...               . .                                    \n"NONE);
		printf(BROWN"**********                                                .   .     t#ft                        .  ..                                                      \n"NONE);
		printf(BROWN"***********************************************************************************************************************************************************\n"NONE);
		usleep(i);
		system("clear");
		/******************************替换#的飞机字符图******************************************/
		printf(WHITE"***********************************************************************************************************************************************************\n"NONE);	
		printf(WHITE"**********                             ..  .                    .. .         ..                      ...            ..  .                                  \n"NONE);
		printf(WHITE"**********                              .                   ..  .             .   E  D            ..  .              .                                     \n"NONE);
		printf(WHITE"**********                               .                  ..                    i   W.          ..                  .                                    \n"NONE);
		printf(WHITE"**********                                                .                    WE               . .                                                        \n"NONE);
		printf(WHITE"**********                                                   .                         W           .                                                       \n"NONE);
		printf(WHITE"**********                                                                                                                                                 \n"NONE);
		printf(WHITE"**********                                                                  W  W                                                                           \n"NONE);
		printf(WHITE"**********                                      .                         W        KKW.Wf                                  .                               \n"NONE);
		printf(WHITE"**********                                   ... .                       i         ...G                                 WKWW  .                            \n"NONE);
		printf(WHITE"**********                                .                   ..   .  W      . W     .K             ..   .          .  W     W                             \n"NONE);
		printf(WHITE"**********                                 .                    .        W  G     WL               .. .              t  .    W                             \n"NONE);
		printf(WHITE"**********                             . .             ,W        G:           W      WE           ...                 W      K                             \n"NONE);
		printf(WHITE"**********                                             i  .   ..  i   W  D       W   W          . . ..       W : W    L                                    \n"NONE);
		printf(WHITE"**********                                         G     ... .          :   W  ;     W           . .          W , K  W                                     \n"NONE);
		printf(WHITE"**********                                               中国航班系统  .       t      D.         .                  EG      W                              \n"NONE);
		printf(WHITE"**********                                         Wecome to airline system           f   WW    E;           W   .         .                               \n"NONE);
		printf(WHITE"**********                                    K                                                  :jK      WWWW     G        E                              \n"NONE);
		printf(WHITE"**********                                   WEW:   温馨提示：请选择登录模式：                                            K                                \n"NONE);
		printf(WHITE"**********                                   ;  K                                                                                                          \n"NONE);
		printf(WHITE"**********                                 :    . W  .          1.输入1进入管理员模式；                                                                    \n"NONE);
		printf(WHITE"**********                                  .    . .j K         2.输入2进入用户模式；                                      .  .                            \n"NONE);
		printf(WHITE"**********                              L G W,.       K         3.输入3进入退出系统；                  .                   .                               \n"NONE);
		printf(WHITE"**********                              Ki .;W i    . K                                               . .               .  .                               \n"NONE);
		printf(WHITE"**********                               , .                 . WWE;    ;K  WK  . .                 .             W  ... .  .                               \n"NONE);
		printf(WHITE"**********                                                .                      W              ..  .  W EK  E        GWt GW                               \n"NONE);
		printf(WHITE"**********                                  W                L                   W     WWW       WW  t                 W ,                                 \n"NONE);
		printf(WHITE"**********                                          G:      :fK                 KW  WW    Wj.                          ;W                                  \n"NONE);
		printf(WHITE"**********                                      W ;:D        EW                fW                                            K;                            \n"NONE);
		printf(WHITE"**********                                     .               KW  j.  ,G  W tW    . .                                     ..                              \n"NONE);
		printf(WHITE"**********                             ..                      K;.           W   .                    ..            ..  .                                  \n"NONE);
		printf(WHITE"**********                              .  .                 . WL            W   .                 .  .              .  .                                  \n"NONE);
		printf(WHITE"**********                                                            j  W LK                                                                              \n"NONE);
		printf(WHITE"**********                                  ...  .              W          W      ...  .                                  ..  .                            \n"NONE);
		printf(WHITE"**********                                 .  .                  .               .  .                                  ..  .                               \n"NONE);
		printf(WHITE"**********                                ....                    .       K     ....                    .               ...                                \n"NONE);
		printf(WHITE"**********                                .                    .  L.     W    . .                   ..   .             .                                   \n"NONE);
		printf(WHITE"**********                              .  .                  . . K           .  .                  . .              .  .                                  \n"NONE);
		printf(WHITE"**********                             . .                  ...    W   K     . .                  ...               . .                                    \n"NONE);
		printf(WHITE"**********                                                .   .     t ft                        .  ..                                                      \n"NONE);
		printf(WHITE"***********************************************************************************************************************************************************\n"NONE);

		usleep(i);
		system("clear");
		/******************************替换G的飞机字符图******************************************/
		printf(LIGHT_BLUE"***********************************************************************************************************************************************************\n"NONE);	
		printf(LIGHT_BLUE"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_BLUE"**********                                                                           D                                                                     \n"NONE);
		printf(LIGHT_BLUE"**********                                                                        i   W                                                                    \n"NONE);
		printf(LIGHT_BLUE"**********                                                                      E                                                                          \n"NONE);
		printf(LIGHT_BLUE"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_BLUE"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_BLUE"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_BLUE"**********                                                                              f                                                                  \n"NONE);
		printf(LIGHT_BLUE"**********                                                               i            G                                                                    \n"NONE);
		printf(LIGHT_BLUE"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_BLUE"**********                                                                  G      L                                 t                                     \n"NONE);
		printf(LIGHT_BLUE"**********                                             ,         G:                   E                                                                    \n"NONE);
		printf(LIGHT_BLUE"**********                                             i          i      D                                     :      L                                    \n"NONE);
		printf(LIGHT_BLUE"**********                                         G                    :      ;                                ,                                          \n"NONE);
		printf(LIGHT_BLUE"**********                                               中国航班系统          t      D                             EG                                     \n"NONE);
		printf(LIGHT_BLUE"**********                                          ecome to airline system           f         E;                                                         \n"NONE);
		printf(LIGHT_BLUE"**********                                                                                       :j                G        E                              \n"NONE);
		printf(LIGHT_BLUE"**********                                    E :   温馨提示：请选择登录模式：                                                                             \n"NONE);
		printf(LIGHT_BLUE"**********                                   ;                                                                                                             \n"NONE);
		printf(LIGHT_BLUE"**********                                 :                    1 输入1进入管理员模式；                                                                    \n"NONE);
		printf(LIGHT_BLUE"**********                                          j           2 输入2进入用户模式；                                                                      \n"NONE);
		printf(LIGHT_BLUE"**********                              L G  ,                  3 输入3进入退出系统；                                                                      \n"NONE);
		printf(LIGHT_BLUE"**********                               i  ;  i                                                                                                           \n"NONE);
		printf(LIGHT_BLUE"**********                               ,                       E;    ;                                                                                   \n"NONE);
		printf(LIGHT_BLUE"**********                                                                                               E   E        G t G                                \n"NONE);
		printf(LIGHT_BLUE"**********                                                   L                                       t                   ,                                 \n"NONE);
		printf(LIGHT_BLUE"**********                                          G:      :f                             j                           ;                                   \n"NONE);
		printf(LIGHT_BLUE"**********                                        ;:D        E                 f                                              ;                            \n"NONE);
		printf(LIGHT_BLUE"**********                                                         j   ,G    t                                                                             \n"NONE);
		printf(LIGHT_BLUE"**********                                                      ;                                                                                          \n"NONE);
		printf(LIGHT_BLUE"**********                                                      L                                                                                          \n"NONE);
		printf(LIGHT_BLUE"**********                                                            j    L                                                                               \n"NONE);
		printf(LIGHT_BLUE"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_BLUE"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_BLUE"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_BLUE"**********                                                        L                                                                                        \n"NONE);
		printf(LIGHT_BLUE"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_BLUE"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_BLUE"**********                                                          t ft                                                                                   \n"NONE);
		printf(LIGHT_BLUE"***********************************************************************************************************************************************************\n"NONE);

		usleep(i);
		system("clear");
		printf(LIGHT_CYAN"***********************************************************************************************************************************************************\n"NONE);	
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                               中国航班系统                                                                                      \n"NONE);
		printf(LIGHT_CYAN"**********                                          Wecome to airline system                                                                               \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                    温馨提示：请选择登录模式：                                                                                   \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                             1 输入1进入管理员模式；                                                                             \n"NONE);
		printf(LIGHT_CYAN"**********                                             2 输入2进入用户模式；                                                                               \n"NONE);
		printf(LIGHT_CYAN"**********                                             3 输入3进入退出系统；                                                                               \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"**********                                                                                                                                                 \n"NONE);
		printf(LIGHT_CYAN"***********************************************************************************************************************************************************\n"NONE);

		usleep(i);
		system("clear");
		/******************************替换G的飞机字符图******************************************/
		i = i+90000;
	}//end while
}//ens Show
